config/routes.rb
Rails.application.routes.draw do
  get 'timer/stop/:id', to: 'timers#stop', as: 'stop_timer'
  resources :timers

  resources :time_logs

  resources :tasks

  get 'projects/assigned', to: 'projects#assigned', as: 'assigned_projects'
  resources :projects

  resources :customers

  devise_for :users

  root 'main#index'

end

app/models/time_log.rb
class TimeLog < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
  has_many :timers
  before_create :create_timer, unless: :seconds
  before_create :set_default_date

  def active_timer
    self.timers.active.first
  end

  private

  def create_timer
    timers.build({start_time: Time.now})
  end
  def set_default_date
    self.date ||= Date.today
  end
end

app/controllers/time_logs_controller.rb
class TimeLogsController < ApplicationController
  before_action :set_time_log, only: [:show, :edit, :update, :destroy]

  # GET /time_logs
  # GET /time_logs.json
  def index
    @time_logs = current_user.time_logs.all.order(:date)
  end

  # GET /time_logs/1
  # GET /time_logs/1.json
  def show
  end

  # GET /time_logs/new
  def new
    @time_log = TimeLog.new
  end

  # GET /time_logs/1/edit
  def edit
  end

  # POST /time_logs
  # POST /time_logs.json
  def create
    @time_log = TimeLog.new(time_log_params)
    
    respond_to do |format|
      if @time_log.save
        format.html { redirect_to @time_log, notice: 'Timer was successfully started.' }
        format.json { render :show, status: :created, location: @time_log }
      else
        format.html { render :new }
        format.json { render json: @time_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_logs/1
  # PATCH/PUT /time_logs/1.json
  def update
    respond_to do |format|
      if @time_log.update(time_log_params)
        format.html { redirect_to @time_log, notice: 'Time log was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_log }
      else
        format.html { render :edit }
        format.json { render json: @time_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_logs/1
  # DELETE /time_logs/1.json
  def destroy
    @time_log.destroy
    respond_to do |format|
      format.html { redirect_to time_logs_url, notice: 'Time log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_log
      @time_log = TimeLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_log_params
      params.require(:time_log).permit(:task_id, :user_id, :date, :seconds, :description)
    end
end

app/helpers/time_logs_helper.rb
module TimeLogsHelper
end

app/views/time_logs/_form.html.erb
<%= semantic_form_for(@time_log) do |f| %>
  <% if @time_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_log.errors.count, "error") %> prohibited this time_log from being saved:</h2>

      <ul>
      <% @time_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.inputs %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_logs/edit.html.erb
<h1>Editing Time Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_log %> |
<%= link_to 'Back', time_logs_path %>

app/views/time_logs/index.html.haml
%h1 Time Logs

%table.table.table-responsive.table-striped
  %thead
    %tr
      %th Project
      %th Task
      %th Date
      %th Duration
      %th Description
      %th{ colspan: "3"}

  %tbody
    - @time_logs.each do |time_log| 
      %tr
        %td= time_log.task.project.name
        %td= time_log.task.name
        %td= time_log.date
        %td= distance_of_time_in_words(time_log.seconds.to_i)
        %td= time_log.description.to_s
        %td= link_to 'Show', time_log 
        %td= link_to 'Edit', edit_time_log_path(time_log) 
        %td= link_to 'Destroy', time_log, method: :delete, data: { confirm: 'Are you sure?' } 

.row &nbsp;

= link_to 'New Time log', new_time_log_path

app/views/time_logs/new.html.erb
<h1>New Time Log</h1>

<%= render 'form' %>

<%= link_to 'Back', time_logs_path %>

app/views/time_logs/show.html.haml
%h1= @time_log.task.name

%h2= "Tracked Time for " + @time_log.date.to_s
%table.table.table-responsive.table-striped
  %thead
    %th Start Time
    %th End Time
    %th Total
  %tbody
    - @time_log.timers.each do |timer|
      %tr
        %td= timer.start_time.to_s
        %td= timer.end_time.to_s
        %td= distance_of_time_in_words(timer.duration)

    %tr
      %td -
      %td -
      %td
        %strong= distance_of_time_in_words(@time_log.seconds.to_i)


= link_to 'Edit', edit_time_log_path(@time_log)
&nbsp;|&nbsp;
= link_to 'Back', time_logs_path 