config/routes.rb
Rails.application.routes.draw do
  get 'timer/stop/:id', to: 'timers#stop', as: 'stop_timer'
  resources :timers

  resources :time_logs

  resources :tasks

  get 'projects/assigned', to: 'projects#assigned', as: 'assigned_projects'
  resources :projects

  resources :customers

  devise_for :users

  root 'main#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :customer
  belongs_to :owner, class_name: "User", foreign_key: "user_id"
  has_and_belongs_to_many :users
  has_many :tasks
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  def assigned
    @projects = current_user.projects
    render :index
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params[:project]
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.haml
%p{id: "notice"}
  = notice 

%h1 Projects

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Customer
      %th Owner
      %th{ colspan: "2"} 
        Actions

  %tbody
    - @projects.each do |project| 
      %tr
        %td= link_to project.name, project
        %td= project.customer.name
        %td= project.owner.full_name

        -if current_user.is_admin?
          %td= link_to 'Edit', edit_project_path(project) 
          %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } 



- if current_user.is_admin?
  = link_to 'New Project', new_project_path

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.haml
%h1= @project.name

%h2 Tasks

= render partial: "shared/show_tasks", locals: {tasks: @project.tasks}





- if current_user.is_admin?
  .row
    .col-md-12
      =link_to "New Task", new_task_path, class: "btn btn-primary"
      
.row
  .col-md-12
    - if current_user.is_admin?
      = link_to 'Edit', edit_project_path(@project) 
      &nbsp;|&nbsp;
    = link_to 'Back', projects_path