config/routes.rb
Rails.application.routes.draw do
  get 'timer/stop/:id', to: 'timers#stop', as: 'stop_timer'
  resources :timers

  resources :time_logs

  resources :tasks

  get 'projects/assigned', to: 'projects#assigned', as: 'assigned_projects'
  resources :projects

  resources :customers

  devise_for :users

  root 'main#index'

end

app/models/timer.rb
class Timer < ActiveRecord::Base
  belongs_to :time_log
  scope :active, -> {where(end_time: nil)}

  def log_time
    self.time_log.update(seconds: self.time_log.seconds.to_i + self.duration.to_i)
  end

  def duration
    self.end_time.to_i - self.start_time.to_i
  end

  def stop
    self.update(end_time: Time.now)
    self.log_time
  end

end

app/controllers/timers_controller.rb
class TimersController < ApplicationController
  before_action :set_timer, only: [:show, :edit, :update, :destroy, :stop]

  # GET /timers
  # GET /timers.json
  def index
    @timers = Timer.all
  end

  # GET /timers/1
  # GET /timers/1.json
  def show
  end

  # GET /timers/new
  def new
    @timer = Timer.new
  end

  # GET /timers/1/edit
  def edit
  end

  # POST /timers
  # POST /timers.json
  def create
    @timer = Timer.new(timer_params)

    respond_to do |format|
      if @timer.save
        format.html { redirect_to tasks_path, notice: 'Timer was successfully started.' }
        format.json { render :show, status: :created, location: @timer }
      else
        format.html { render :new }
        format.json { render json: @timer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timers/1
  # PATCH/PUT /timers/1.json
  def update
    respond_to do |format|
      if @timer.update(timer_params)
        format.html { redirect_to @timer, notice: 'Timer was successfully updated.' }
        format.json { render :show, status: :ok, location: @timer }
      else
        format.html { render :edit }
        format.json { render json: @timer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timers/1
  # DELETE /timers/1.json
  def destroy
    @timer.destroy
    respond_to do |format|
      format.html { redirect_to timers_url, notice: 'Timer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def stop
    if @timer.stop
      flash[:success] = "Timer has been stopped."
    else
      flash[:error] = "Oops, unable to stop timer."
    end
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timer
      @timer = Timer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timer_params
      params.require(:timer).permit(:start_time, :time_log_id)
    end
end

app/helpers/timers_helper.rb
module TimersHelper
end

app/views/timers/_form.html.erb
<%= form_for(@timer) do |f| %>
  <% if @timer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timer.errors.count, "error") %> prohibited this timer from being saved:</h2>

      <ul>
      <% @timer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timers/edit.html.erb
<h1>Editing Timer</h1>

<%= render 'form' %>

<%= link_to 'Show', @timer %> |
<%= link_to 'Back', timers_path %>

app/views/timers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Timers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timers.each do |timer| %>
      <tr>
        <td><%= link_to 'Show', timer %></td>
        <td><%= link_to 'Edit', edit_timer_path(timer) %></td>
        <td><%= link_to 'Destroy', timer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timer', new_timer_path %>

app/views/timers/new.html.erb
<h1>New Timer</h1>

<%= render 'form' %>

<%= link_to 'Back', timers_path %>

app/views/timers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_timer_path(@timer) %> |
<%= link_to 'Back', timers_path %>